CREATE TABLE IF NOT EXISTS Perfil (
	Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(256),
	UrlImagen VARCHAR(256),
	Nacionalidad VARCHAR(256),
	Cuenta_Email VARCHAR(256) NOT NULL,
	FOREIGN KEY (Cuenta_Email) REFERENCES Cuenta(Email) ON DELETE CASCADE
);
