CREATE TABLE IF NOT EXISTS Ubicacion (
	Latitude FLOAT( 10, 6 ) NOT NULL ,
  	Longitude FLOAT( 10, 6 ) NOT NULL,
  	Perfil_Id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  	FOREIGN KEY (Perfil_Id) REFERENCES Perfil(Id) ON DELETE CASCADE
);