CREATE TABLE IF NOT EXISTS Prestamo (
	Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Estado INT NOT NULL,
	FechaEnvio DATETIME,
	FechaRecepcion DATETIME,
	FechaExpiracion DATETIME,
	CalificacionAlReceptor INT,
	CalificacionAlPrestamista INT,
	UltimaModificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Item_Id BIGINT UNSIGNED NOT NULL,
    Prestamista_Id BIGINT UNSIGNED NOT NULL,
    Receptor_Id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY(Item_Id) REFERENCES Item(Id) ON DELETE CASCADE,
    FOREIGN KEY(Prestamista_Id) REFERENCES Perfil(Id) ON DELETE CASCADE,
    FOREIGN KEY(Receptor_Id) REFERENCES Perfil(Id) ON DELETE CASCADE
);