CREATE TABLE IF NOT EXISTS Comentario (
	Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Texto TEXT,
	FechaCreacion DATETIME,
	Prestamo_Id BIGINT UNSIGNED NOT NULL,
    Perfil_Id	BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (Perfil_Id) REFERENCES perfil(Id) ON DELETE CASCADE,
	FOREIGN KEY (Prestamo_Id) REFERENCES Prestamo(Id) ON DELETE CASCADE
);