CREATE TABLE IF NOT EXISTS Autor_Item (
	Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Autor_Id BIGINT UNSIGNED NOT NULL,
	Item_Id BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (Autor_Id) REFERENCES Autor(Id),
	FOREIGN KEY (Item_Id) REFERENCES Item(Id) ON DELETE CASCADE
);